### ISSUE TITLE
AMD Adrenalin 23.8.1 issues after upgrading from 22.5.1

### ISSUE THREAD

**Issue by antoniodesousa** [teknogods/TeknoParrotUI#518]
Hi, after I updated my graphics card driver from 22.5.1 to 23.8.1, I'm getting all kind of weird issues:

- All Initial D games don't boot at all
- The House of the Dead 4 just shows a black screen
- Sega Rally 3 works but no sound (it has sound on 22.5.1 🤷)
- Sega Race TV just shows black screen
- OutRun SP SDX crashes TeknoParrot with some error

Games that work without issues:

- Contra: Evolution
- Daytona Championship USA - NSE
- House of the Dead: Scarlet Dawn

Downgrading to version 22.5.1 is not an option since performance is very visible compared to 23.8.1 in many games/emulators.

My PC specs:
AMD Ryzen 9 6900hx
AMD Radeon RX 6600m
64GB RAM DDR5 + 2TB SSD Samsung 980 Pro
Windows 11 Pro
TeknoParrot 1.0.0.1074 (latest as of today)

**Comment by Nezarn** [comment]
> All Initial D games don't boot at all
    The House of the Dead 4 just shows a black screen
    Sega Rally 3 works but no sound (it has sound on 22.5.1 🤷)
    Sega Race TV just shows black screen
    OutRun SP SDX crashes TeknoParrot with some error

Multiple games are getting worked on, but it doesn't help that amd randomly breaks stuff with each driver update. (for example older IDAS games crash because of a driver bug (workaround is being worked on, but will take a very long time, in the meantime you can boot the game with the old fix if you don't use vshigeno*, vedge*, vshadowmap* files from the fix, you will have missing characters in cutscenes tho), 0 should work)

> OutRun SP SDX crashes TeknoParrot with some error

Also "with some error" is not really helpful.

**Comment by antoniodesousa** [comment]
Thanks for the reply. And yes, AMD drivers are kinda annoying. They fix something and break others. I'm starting to regret have bought an AMD GPU 😞 

About OutRun, I'm not getting the exception anymore for some reason. Now I'm getting another problem:

![Screenshot 25_08_2023 14_09_32](https://github.com/teknogods/TeknoParrotUI/assets/10920974/53688e7a-29df-4b0b-82b8-fc74942f67bb)

There are no errors besides that dialog.

**Comment by nixxou** [comment]
You can use those games in 23.10 with amernime zone drivers but you got to switch to legacy opengl before and that's kinda annoying.
![image](https://github.com/teknogods/TeknoParrotUI/assets/45721836/bfb6fe4e-4015-4a31-a2d9-9cada8537e56)

I guess it should be doable to sideload amd legacy opengl dll and avoid this, but when i ask for help about that in discord, it doesn't seems to trigger any interest

**Comment by Nezarn** [comment]
Sega Race TV is fixed on latest TeknoParrot version, grab the shaderfix from our discord

**Comment by antoniodesousa** [comment]
Hi @Nezarn, I just tested the new shaderfix + latest TeknoParrot updates:

- Copy the cold.pac file into data/cold folder
- Changed the "Graphics - GPU Fix" to "New AMD Driver"

But I get the dialog "ElfLoader is not responding". In the BungieLoader console, it shows "amLibInit: cannot open /proc/bus/pci/00/1f.0".

**Comment by Nezarn** [comment]
> In the BungieLoader console, it shows "amLibInit: cannot open /proc/bus/pci/00/1f.0".

Thats not related at all (that error can be ignored), tested on 2 AMD based PCs, and some other users said already that it works.

Maybe theres a problem with your install. (I suspect same issue causes Outrun 2 to be not responding either, not related to amd driver)

**Comment by antoniodesousa** [comment]
Hmm I uninstall the driver using the AMD Cleanup Utility and reinstall 23.8.1 again, and reinstall TeknoParrot from scratch... still doesn't work for me "ElfLoader is not responding". OutRun shows this error in the console "## OpenGL Error (null)(0502)(predrawFilterShader:539)".

Both games work fine using Adrenalin 22.5.1. Is possible to output a more verbose logging? "ElfLoader is not responding" doesn't really help much.

**Comment by Iachino87** [comment]
same here, sega race tv works ok with last tp (with fix) and last amd driver, but house fo the dead 4 has a black screen.

**Comment by antoniodesousa** [comment]
> same here, sega race tv works ok with last tp (with fix) and last amd driver

What are your PC specs?

**Comment by Iachino87** [comment]
My PC specs:
Intel Core I5 4570
AMD Radeon RX 560
8GB RAM DDR3 + 250 SSD 
Windows 10 Pro
TeknoParrot 1.0.0.1075 (latest as of today)

**Comment by antoniodesousa** [comment]
Thanks, your specs are very different from my PC. I guess the new patch doesn't work with all AMD configurations. Maybe, my CPU is the culprit since it has an iGPU (apart from my dedicated GPU)? Anyways, it sucks 😢

**Comment by nzgamer41** [comment]
sega race tv works fine for me with Nezarn's new fix, RX 580, Windows 10, latest TP, AMD driver 23.7.2. Maybe your dump is bad?

**Comment by Iachino87** [comment]
> sega race tv works fine for me with Nezarn's new fix, RX 580, Windows 10, latest TP, AMD driver 23.7.2. Maybe your dump is bad?

sure is it a bad dump.

still has a lot of graphical glitches on 2spicy, rambo (a lot of month ago was a really good gameplay, why? is it for amd?)

**Comment by antoniodesousa** [comment]
It's not a bad dump... I played the game using Adrenalin 22.5.1 before upgrade to 23.8.1. I even tested it yesterday with the new fix + "New AMD Driver" enabled and it worked right away using the 22.5.1 driver. I get all my dumps from a very trustfully source. For example, my OutRun SP SDX dump is not that tempered garbage with the Initial D soundtrack that is circulating everywhere. Sadly, the performance difference between 22.5.1 and 23.8.1 is very evident in many of the emulators and games that I play/use. So, it's not worth to downgrade to 22.5.1 just to play some arcade games.

You both use a really old AMD GPU +6 years old. I'm using the RX 6600. I'm pretty sure that there are some compatibility issues with the new fix for my card. It would be nice if I could get a more detailed log of what exactly the issue is when I boot the game, besides the stupid dialog "ElfLoader is not responding".

And by the way, I tested 3 different dumps of Sega Race TV just to be sure that it wasn't my dump. Same error in all 3.

**Comment by Nezarn** [comment]
> You both use a really old AMD GPU +6 years old. I'm using the RX 6600. I'm pretty sure that there are some compatibility issues with the new fix for my card. It would be nice if I could get a more detailed log of what exactly the issue is when I boot the game, besides the stupid dialog "ElfLoader is not responding".

@antoniodesousa Fix was made and tested on a RDNA3 GPU. 
Also usually AMD driver issue would result in crash and not "not responding" msg.
Are you sure you aren't using any extra patches for the game? (game runs in a small 640x480 resolution by default)

> still has a lot of graphical glitches on 2spicy, rambo (a lot of month ago was a really good gameplay, why? is it for amd?)

@lachino87 Since those don't have updated fix, obviously they won't work for now on newer driver. (Rambo is not a priority on my TODO list since a guy stole my old fix, changed 1 file, removed readme file that included credits and calling the fix his own)

**Comment by antoniodesousa** [comment]
> Are you sure you aren't using any extra patches for the game? (game runs in a small 640x480 resolution by default)

Hi @Nezarn, I'm using the original unpatched `drive.elf` file (CRC32 179B2FA0). I can send it you the file in discord if that helps something. Curiously, deleting the `cold.pac` file doesn't seem to affect anything. 🤷‍♂️ 

I already tried everything besides reinstalling Windows 11, but that would be a really pain in the ass...

**Comment by Iachino87** [comment]
i just updated to 23.8.2 : hotd4and sega race tv works ok! AWESOME !!!

**Comment by Arapose** [comment]
Here are my tests of the Sega Lindbergh games on my new AMD drivers:

The House of the Dead 4, both original and Special, worked perfectly fine
Virtua Fighter 5 is completely glitched up, with half the screen being broken afterimages
After Burner Climax crashes when the system startup was finished
Let's Go Jungle, both original and Special, worked nicely enough, with the only graphical issues being the flies and the paddles being invisible
2Spicy is completely glitched with broken shading and invisible character models
OutRun 2 SP works perfectly intact
Initial D Arcade Stage 4-5 crashes upon booting up
R-Tuned works perfectly intact
Sega Race TV also works perfect with the new AMD fix patch
Rambo worked nicely on my AMD drivers

**Comment by nixxou** [comment]
I get initial D running with my 23.10 amernimezone drivers. Should work with the 23.11 too.
![image](https://github.com/teknogods/TeknoParrotUI/assets/45721836/52c36f9c-d8b3-4901-8838-85d972c33e6f)

Basically, you install the drivers, you go here and option 11 : 
![image](https://github.com/teknogods/TeknoParrotUI/assets/45721836/bfb6fe4e-4015-4a31-a2d9-9cada8537e56)

In the drivers folder, you look for files *2210.dll
![image](https://github.com/teknogods/TeknoParrotUI/assets/45721836/2bc405bf-6a81-4cfa-8ac9-541ed7e85c2a)

Copy them into your game folder, remove the _2210 part
![image](https://github.com/teknogods/TeknoParrotUI/assets/45721836/b9d85037-11ed-488b-af07-2b7c4a3143a8)

And done, your game will use the old opengl renderer. But the new opengl renderer still apply by default for other games.

**Comment by antoniodesousa** [comment]
Today, I installed the latest driver update 23.12.1, and almost all the games that had problems work fine now:

Games that still don't work:
- Initial D: Arcade Stage 4 to 8 just show black screen before closing

Games that work fine:
- Contra: Evolution
- Daytona Championship USA
- Daytona Championship USA - NSE
- House of the Dead: Scarlet Down
- Initial D: Arcade Stage Zero Ver. 2
- Justice League - Heroes United
- OutRun 2 SP SDX
- SEGA Race TV
- SEGA Racing Classic
- SEGA Rally 3
- Spiderman
- The House of the Dead 4 (some graphical issues in several places)
- The House of the Dead 4 Special (some graphical issues in several places)
- Virtua Fighter esports

I'm very happy 😄

**Comment by antoniodesousa** [comment]
Initial D 4 - 8 are now working with the new AMD fix!! Finally, I can play those games again 😄 
There's only a small issue in the cutscenes. The 3D models of the characters don't show up. Only affects Initial D 4 - 6, since 7 and 8 uses plain images. It doesn't affect the gameplay whatsoever though.

**Comment by Nezarn** [comment]
> The 3D models of the characters don't show up. Only affects Initial D 4 - 6, since 7 and 8 uses plain images. It doesn't affect the gameplay whatsoever though.

Thats intended, blame AMD for making worse than Intel drivers. (characters are causing AMD drivers to crash the game), maybe someday when they manage to make their driver work at least as much as Intel drivers, you could use the normal AMD option for the fix, which has characters working fine just like with old driver.

**Comment by antoniodesousa** [comment]
> Thats intended, blame AMD for making worse than Intel drivers. (characters are causing AMD drivers to crash the game), maybe someday when they manage to make their driver work at least as much as Intel drivers, you could use the normal AMD option for the fix, which has characters working fine just like with old driver.

Oh I see, thanks for the explanation. It's not a big deal anyways. I'm very happy that I can play those games again 😄

**Comment by marcosgaming10** [comment]
Hi guys, i apply new Fix of Nezarn on Sega Race TV ...
Copy the cold.pac file into data/cold folder
Changed the "Graphics - GPU Fix" to "New AMD Driver"
But i have always same problems graphic. The Game it's unplayable for me.
How to fix ?? There is other way ??

**Comment by antoniodesousa** [comment]
Maybe bad dump? It works for me.

**Comment by marcosgaming10** [comment]
I don't think. Please where you find the good dump? Inviata dal mio telefono-------- Messaggio originale --------Da: Antonio de Sousa ***@***.***>Data: dom 12 mag 2024, 21:01A: teknogods/TeknoParrotUI ***@***.***>Cc: marcosgaming10 ***@***.***>, Comment ***@***.***>Oggetto: Re: [teknogods/TeknoParrotUI] AMD Adrenalin 23.8.1 issues after upgrading from 22.5.1 (Issue #518)
Maybe bad dump? It works for me.

**Comment by dlimapt** [comment]
Same issue still happening in Adrenalin 24.3.1 (Radeon RX580).

All "linux based" dumps that use legacy "BudgieLoader.exe" hang (blank screen) and crash (Elf loader not responding) upon loading.
"windows based" based dumps work with no issues.
Everyting worked flawlessly in previous Adrenalin versions.



GAELCO PC BASED
	Gaelco Championship Tuning Race - NOK
	Tokyo Cop - NOK

SEGA LINDBERGH RED EX
	Rambo - NOK
	Star Trek Voyager - NOK
	Too Spicy - NOK
	
Sega Lindbergh Yellow
	Afterburner Climax - NOK
	House of the Dead 4 - NOK
	Initial D 4 Export - NOK
	Initial D 5 Export - NOK
	Let's Go Jungle - NOK
	Lets Go Jungle Special - NOK
	Outrun 2 Special Tours Deluxe - NOK
	R-Tuned Ultimate Street Racing - NOK
	Sega Lets Go Island 3D - NOK
	Sega Race TV - NOK
	The House of the Dead 4 Special - NOK
	Virtua Fighter 5 Rev B - NOK
	Virtua Fighter 5 Rev C - NOK
	Virtua Tennis 3 - NOK

**Comment by nixxou** [comment]
Not an expert here, but RX580 is polaris, support is pretty much dropped by amd (it's on extended support), so it often use older version of the driver under the hood and you wont get some of the features and fix, just security update.

> "The AMD Polaris and Vega graphics architectures are mature, stable and performant and don't benefit as much from regular software tuning. Going forward, AMD is providing critical updates for Polaris- and Vega-based products via a separate driver package, including important security and functionality updates as available. The committed support is greater than for products AMD categorizes as legacy, and gamers can still enjoy their favourite games on Polaris and Vega-based products."
